Fix build error on OS X 10.8
I was getting the following errors building on 10.8:

    dome_key_event_source_simulator/dome_key_event_source_simulator.h:56:31: error: unknown type name 'NSEventModifierFlags'
    void dkess_press_key(int key, NSEventModifierFlags modifier_flags);
                                  ^
    dome_key_event_source_simulator/dome_key_event_source_simulator.m:66:31: error: unknown type name 'NSEventModifierFlags'
    void dkess_press_key(int key, NSEventModifierFlags modifier_flags) {

Turns out `NSEventModifierFlags` doesn't exist before 10.10. Before
then, it was just an `NSUInteger`.